### PR TITLE
🎉🎉🎉🎉🎉🎉 fixed 🎉🎉🎉🎉🎉🎉

### PR DESCRIPTION
**Pull request by MylesBorins**
This will get landed when things are fixed!

### CODE REVIEW

**Comment by MylesBorins** [comment]
### Expected behavior:

So we should be able to copy the link referenced to by the sha [f06ae59](https://github.com/mylesborins/explain-broken-url/pull/1/commits/f06ae59ea5401861c3b3a1f86aa702229911a22c) above append .patch and receive a patch that can be applied with `git am`

Original schema is `:user/:repo/pull/:number/commits/:hash`

The Patch schema is `:user/:repo/pull/:number/commits/:hash.patch`

### Actual Behavior:

As you can see the patch schema does not work [for commit f06ae59](https://github.com/mylesborins/explain-broken-url/pull/1/commits/f06ae59ea5401861c3b3a1f86aa702229911a22c.patch)

You instead an error handling screen from the new UI you launched today 🎉🎉🎉🎉

**Comment by MylesBorins** [comment]
### Reproducible solution

Alternatively if we were to use the schema `:user/:repo/commit/number/:hash` then things start to work

https://github.com/mylesborins/explain-broken-url/commit/f06ae59ea5401861c3b3a1f86aa702229911a22c still links to the commit we expect
https://github.com/mylesborins/explain-broken-url/commit/f06ae59ea5401861c3b3a1f86aa702229911a22c.patch links to the patch

I think that is probably enough to figure out how to fix it :smile:

**Comment by kivikakk** [comment]
Fixed! 😸

* https://github.com/mylesborins/explain-broken-url/pull/1/commits/f06ae59ea5401861c3b3a1f86aa702229911a22c.patch
* https://github.com/mylesborins/explain-broken-url/pull/1/commits/f06ae59ea5401861c3b3a1f86aa702229911a22c.diff

**Comment by MylesBorins** [comment]
This is so rad. Thanks!!!!

**Pull request closed without merging**
